defaults:
  - _base_

deter: 4096
hidden: 512
discrete: 32
depth: 32
units: 512
act: 'SiLU'
norm: True

compile: False

graph:
  enabled: True
  n_max: 8
  e_max: 168
  simple_units: 512
  semantic_dim: 512
  decoder_units: 256
  bbox_query_dim: 4

progress:
  enabled: True
  beta: 0.05
  beta_warmup_start: 400000
  beta_warmup_end: 700000

loss_scales:
  node: 1.0
  nodetgt: 1.0
  relabs: 1.0
  reltemp: 1.0
  graphdyn: 1.0
  graphrep: 0.05
  progress_value: 1.0
  progress_model: 1.0
