task: maniskill_PickCube-v1
steps: 4e6
env_num: 200
eval_episode_num: 10
action_repeat: 1
train_ratio: 64
time_limit: 0

seed: ${seed}
device: ${device}

eval_time_limit: 0

eval_render_size: [512, 512]
obs_mode: rgb+segmentation
sim_backend: gpu
control_mode: pd_joint_delta_pos
reward_mode: normalized_dense
reward_fallback: [sparse]
shader_dir: minimal
nonprivileged_obs: false
sim_config: {}
size: [112, 112]
robot_uids: ''
cameras: []

encoder:
  mlp_keys: '^state$'
  cnn_keys: '^image_'
decoder:
  mlp_keys: '^state$'
  cnn_keys: '^image_'

progress_mode: task_schedule

graph:
  enabled: ${model.graph.enabled}
  mshab_task: ${env.task}
  entity_vocab: ${model.graph.entity_vocab}
  use_target_flag: false
  object_object_spatial: true
  disable_object_object_relations: false
  thresholds_path: ''
  whitelist_dir: ''
  visibility_policy: keep_tabletop
  n_max: ${model.graph.n_max}
  e_max: ${model.graph.e_max}
  bypass_teemo: false
